#!/bin/bash
echo "=========================================="
echo "CRON JOBS STATUS REPORT"
echo "=========================================="
echo ""
echo "📅 Current Date/Time: $(date '+%Y-%m-%d %H:%M:%S %Z')"
echo ""
echo "✅ SCHEDULED CRON JOBS:"
echo "----------------------------------------"
crontab -l | grep -E "(daily_workflow|daily_leads|daily_monthly|manual_sla|nifty_price)" | while read line; do
    schedule=$(echo "$line" | awk '{print $1, $2, $3, $4, $5}')
    script=$(echo "$line" | awk '{for(i=6;i<=NF;i++) if($i ~ /\.py$/) print $i}')
    echo "  • $script"
    echo "    Schedule: $schedule"
    echo ""
done
echo ""
echo "📧 EMAIL CONFIGURATION:"
echo "----------------------------------------"
echo "  Server: 65-254-81-55.cprapid.com:993"
echo "  From: anshul@inertiainvest.in"
echo "  TLS: Enabled"
echo ""
echo "📊 LAST RUN STATUS:"
echo "----------------------------------------"
echo "  Daily Leads Report:"
tail -5 /home/inertia/app/logs/daily_leads_report.log 2>/dev/null | grep -E "(✅|❌|completed|failed)" | tail -1 || echo "    No recent logs"
echo ""
echo "  Daily Monthly Investments Report:"
tail -5 /home/inertia/app/logs/daily_monthly_investments_report.log 2>/dev/null | grep -E "(✅|❌|completed|failed)" | tail -1 || echo "    No recent logs"
echo ""
echo "  Daily Workflow Report:"
tail -5 /home/inertia/app/logs/daily_report.log 2>/dev/null | grep -E "(✅|❌|completed|failed)" | tail -1 || echo "    No recent logs"
echo ""
echo "=========================================="
