#!/usr/bin/env python3
"""
Scaffold a host .env when moving any working Inertia install to a new server.

Default: same DB names/user/host as the source install; generate new SECRET_KEY
and DB_PASSWORD. Does not read an existing production .env.

  python3 scripts/deployment/generate_host_env.py --out /tmp/inertia-new-host.env
  python3 scripts/deployment/generate_host_env.py --db-password '...' --secret-key '...'
"""
from __future__ import annotations

import argparse
import secrets
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
EXAMPLE = ROOT / ".env.example"


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--out", type=Path, required=True, help="Write path (e.g. /tmp/inertia-new-host.env)")
    p.add_argument("--db-name", default="inertia_app2025")
    p.add_argument("--db-user", default="inertia_app")
    p.add_argument("--db-host", default="127.0.0.1")
    p.add_argument("--db-port", default="3306")
    p.add_argument("--db-password", default="", help="If empty, generate a strong password")
    p.add_argument("--secret-key", default="", help="If empty, generate")
    p.add_argument("--email-source-tag", default="", help='e.g. "Lean spare" — empty omits line')
    p.add_argument(
        "--session-cookie-secure",
        default="false",
        choices=("true", "false"),
        help="false for HTTP IP smoke; true after HTTPS/DNS",
    )
    p.add_argument("--flask-env", default="production")
    args = p.parse_args()

    db_password = args.db_password or secrets.token_urlsafe(24)
    secret_key = args.secret_key or secrets.token_urlsafe(48)

    lines = [
        "# Generated by scripts/deployment/generate_host_env.py — fill MAIL_* and integrations",
        "# Do not commit this file.",
        f"FLASK_ENV={args.flask_env}",
        "FLASK_APP=main.py",
        f"SECRET_KEY={secret_key}",
        "",
        f"DB_USER={args.db_user}",
        f"DB_PASSWORD={db_password}",
        f"DB_HOST={args.db_host}",
        f"DB_PORT={args.db_port}",
        f"DB_NAME={args.db_name}",
        "",
        "MAIL_SERVER=smtp.gmail.com",
        "MAIL_PORT=587",
        "MAIL_USE_TLS=True",
        "MAIL_USE_SSL=False",
        "MAIL_USERNAME=",
        "MAIL_PASSWORD=",
        "MAIL_DEFAULT_SENDER=",
        "",
    ]
    if args.email_source_tag.strip():
        # Quote if spaces so systemd EnvironmentFile / shell sourcing stay safe
        tag = args.email_source_tag.strip()
        if " " in tag and not (tag.startswith('"') or tag.startswith("'")):
            tag = f'"{tag}"'
        lines.append(f"EMAIL_SOURCE_TAG={tag}")
        lines.append("")

    lines.extend(
        [
            f"SESSION_COOKIE_SECURE={args.session_cookie_secure}",
            f"REMEMBER_COOKIE_SECURE={args.session_cookie_secure}",
            "WTF_CSRF_ENABLED=True",
            "FORCE_2FA_FOR_ALL_USERS=true",
            "",
            "ENABLE_AI_SERVICES=false",
            "OLLAMA_ENABLED=false",
            "OLLAMA_BASE_URL=",
            "LLM_FALLBACK_TO_OLLAMA=false",
            "PORTFOLIO_REVIEW_HYBRID_SKIP_LLM=true",
            "",
            "DI_CREATE_OPS_TASKS=false",
            "",
        ]
    )

    if EXAMPLE.is_file():
        lines.append(f"# See also keys in {EXAMPLE.name} for optional integrations.")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    try:
        args.out.chmod(0o600)
    except OSError:
        pass

    print(f"Wrote {args.out} (mode 600 if supported)")
    print("Generated SECRET_KEY and DB_PASSWORD are inside that file — copy to the server over SSH only.")
    print("Fill MAIL_* (and Drive/Zoho/etc.) before go-live.")
    if not args.db_password:
        print("(DB_PASSWORD was auto-generated)")
    if not args.secret_key:
        print("(SECRET_KEY was auto-generated)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
